// Build: roll up the modular src/ crawler into the single shipped crawl.js (AD-081/082).
// Runtime stays zero-install (Node built-ins only); esbuild is a devDependency used
// at build time only. Source of truth is src/; the root crawl.js is a generated artifact.
import { build } from "esbuild";

await build({
  entryPoints: ["src/crawl.js"],
  bundle: true,
  platform: "node",
  target: "node14",
  outfile: "crawl.js",
  banner: { js: "#!/usr/bin/env node\n// GENERATED from src/ by `npm run build` — do not edit this file directly." },
  legalComments: "none",
});
console.log("built crawl.js from src/");
